/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package analisisentimen.boundary;

import analisisentimen.control.Corpus;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import analisisentimen.control.DocumentReader;
import analisisentimen.control.Evaluator;
import analisisentimen.control.HMMProb;
import analisisentimen.control.KFoldCrossValidation;
import analisisentimen.control.Viterbi;
import analisisentimen.control.Weighting;
import analisisentimen.control.WeightingPOS;
import analisisentimen.entity.Tweet;
import java.util.List;
import java.util.Random;
import javax.swing.table.DefaultTableModel;
//import postaggermnb.control.Normalisasi;
/**
 *
 * @author Asus
 */
public class MainFrame extends javax.swing.JFrame {
    private static final HMMProb hmmProbab = new HMMProb();
    private String selectedFile;
    private DefaultTableModel modelBobot;  
    private DocumentReader dr;
    private static KFoldCrossValidation kFoldCV;
    private List<Tweet> tweetList;
//    private static DocumentReader tweet = new DocumentReader();
    Weighting pembobotan;
    WeightingPOS pembobotanPOS;

    /** Creates new form MainFrame */
    public MainFrame() {
        initComponents();
        prosesBtn.setEnabled(false);
        
        mnbRB.setEnabled(false);
        mnbPosRB.setEnabled(false);
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        klasifikasi = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        nameFile = new javax.swing.JTextField();
        loadBtn = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        mnbRB = new javax.swing.JRadioButton();
        mnbPosRB = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        prosesBtn = new javax.swing.JButton();
        testBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        klasifikasiTable2 = new javax.swing.JTable();
        jScrollPane7 = new javax.swing.JScrollPane();
        klasifikasiTable1 = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nameFile.setPreferredSize(new java.awt.Dimension(94, 39));
        nameFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFileActionPerformed(evt);
            }
        });
        jPanel3.add(nameFile, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 19, 290, 30));

        loadBtn.setText("Load");
        loadBtn.setPreferredSize(new java.awt.Dimension(93, 39));
        loadBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadBtnActionPerformed(evt);
            }
        });
        jPanel3.add(loadBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 70, 30));

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));
        jPanel6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroup1.add(mnbRB);
        mnbRB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        mnbRB.setForeground(new java.awt.Color(51, 51, 51));
        mnbRB.setText("MNB");
        mnbRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnbRBActionPerformed(evt);
            }
        });
        jPanel6.add(mnbRB, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        buttonGroup1.add(mnbPosRB);
        mnbPosRB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        mnbPosRB.setForeground(new java.awt.Color(51, 51, 51));
        mnbPosRB.setText("MNB (POS Tagging)");
        mnbPosRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnbPosRBActionPerformed(evt);
            }
        });
        jPanel6.add(mnbPosRB, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Klasifikasi");

        prosesBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        prosesBtn.setText("Train");
        prosesBtn.setPreferredSize(new java.awt.Dimension(65, 29));
        prosesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prosesBtnActionPerformed(evt);
            }
        });

        testBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        testBtn.setText("Test");
        testBtn.setPreferredSize(new java.awt.Dimension(65, 29));
        testBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testBtnActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setPreferredSize(new java.awt.Dimension(216, 202));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 55, 90, 31));

        jLabel5.setText("Precision");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jLabel6.setText("Recall");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 101, -1, 18));

        jLabel7.setText("F-Measure");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jLabel8.setText("Accurascy");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 175, -1, 31));

        jTextField6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 95, 90, 31));

        jTextField7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 175, 90, 31));

        jTextField8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 135, 90, 31));

        jTextField3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 55, 90, 31));

        jTextField9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 95, 90, 31));

        jTextField10.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 135, 90, 31));

        jTextField11.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 175, 90, 31));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("MNB");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 19, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("MNB (POS Tagging)");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Evaluasi");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Dataset");

        javax.swing.GroupLayout klasifikasiLayout = new javax.swing.GroupLayout(klasifikasi);
        klasifikasi.setLayout(klasifikasiLayout);
        klasifikasiLayout.setHorizontalGroup(
            klasifikasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(klasifikasiLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(klasifikasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(klasifikasiLayout.createSequentialGroup()
                        .addGroup(klasifikasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel9)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)
                            .addComponent(jLabel3)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(6, 6, 6))
                    .addGroup(klasifikasiLayout.createSequentialGroup()
                        .addComponent(prosesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addComponent(testBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        klasifikasiLayout.setVerticalGroup(
            klasifikasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(klasifikasiLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addGroup(klasifikasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prosesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(testBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Hasil Pengujian MNB");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jLabel17.setText("Waktu Eksekusi :");

        klasifikasiTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane5.setViewportView(klasifikasiTable2);

        klasifikasiTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane7.setViewportView(klasifikasiTable1);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("Hasil Pengujian MNB (POS Tagging)");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jLabel18.setText("Waktu Eksekusi :");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addGap(45, 45, 45))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel15)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 699, Short.MAX_VALUE)
                    .addComponent(jScrollPane5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                    .addContainerGap(566, Short.MAX_VALUE)
                    .addComponent(jLabel18)
                    .addGap(52, 52, 52)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jLabel17)
                .addGap(17, 17, 17)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                    .addContainerGap(790, Short.MAX_VALUE)
                    .addComponent(jLabel18)
                    .addGap(39, 39, 39)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(klasifikasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(klasifikasi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFileActionPerformed

    private void mnbRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnbRBActionPerformed
        // TODO add your handling code here:
        if(mnbRB.isSelected()){
            prosesBtn.setEnabled(true);
            testBtn.setEnabled(false);
        }
    }//GEN-LAST:event_mnbRBActionPerformed
    
    public void doProses (List<Tweet> tweetList) throws IOException {
        KFoldCrossValidation kFoldCV = new KFoldCrossValidation(10, tweetList);
        kFoldCV.shuffle(new Random(), tweetList);
        
        int folds = kFoldCV.getFolds();
        System.out.format("Number of folds: %s\n\n", folds);
        
        
        for (int i = 0; i < folds; ++i) {
            List<Tweet> testingSet = kFoldCV.getTrainingSet(i);
            Weighting bobot = new Weighting(testingSet);
            bobot.doPembobotan();
            Evaluator evaluator = new Evaluator(testingSet, bobot);
            
            //System.out.format("Fold: %s, Accuracy: %s\n", i, bobot.getHasilPembobotan());
            System.out.format("Fold: %s", i);
            System.out.println();
        }
    }

    
    private void prosesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prosesBtnActionPerformed
        if(mnbRB.isSelected()) {
            dr = new DocumentReader(selectedFile);
            try {
                dr.readTweetSet();
            } catch (IOException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            tweetList = dr.getTweetList();
            try {
                //System.out.println(tweetList);
                doProses(tweetList);
            } catch (IOException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        } else if(mnbPosRB.isSelected()) {
            
            
        }

    }//GEN-LAST:event_prosesBtnActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void loadBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadBtnActionPerformed
        // TODO add your handling code here:
        prosesBtn.setEnabled(false);
        testBtn.setEnabled(false);
        mnbRB.setEnabled(true);
        mnbPosRB.setEnabled(true);
        
        JFileChooser chooser = new JFileChooser();
        chooser.setDialogTitle("Pilih File");
        chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        chooser.setAcceptAllFileFilterUsed(false);
        chooser.setCurrentDirectory(new File(System.getProperty("user.dir")));
        
        if (chooser.showOpenDialog(null)==JFileChooser.APPROVE_OPTION){
            try{
                selectedFile = String.valueOf(chooser.getSelectedFile());
                nameFile.setText(selectedFile);
                System.out.println("Selected File: " + selectedFile);
                
                
                //Pembobotan tanpa menerapkan POS Tagging
//                pembobotan = new Weighting(selectedFile);
//                pembobotan.doPembobotan();
//                double [][] data = pembobotan.transpose(pembobotan.getHasilPembobotan());
                //KFoldCrossValidation kfold = new KFoldCrossValidation(data);
                
                //Pembobotan berdasarkan POS Tagging
//                pembobotanPOS = new WeightingPOS(selectedFile);
//                pembobotanPOS.doPembobotan();
                

            } catch (NullPointerException e) {
                    JOptionPane.showMessageDialog(null, "format file not .txt", "Failed", JOptionPane.ERROR_MESSAGE);
            }
        } else {
                            System.out.println("Failed");

        }
        
    }//GEN-LAST:event_loadBtnActionPerformed

    private void mnbPosRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnbPosRBActionPerformed
        // TODO add your handling code here:
        if(mnbPosRB.isSelected()){
            prosesBtn.setEnabled(true);
            testBtn.setEnabled(false);
        }
        
        
    }//GEN-LAST:event_mnbPosRBActionPerformed

    private void testBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testBtnActionPerformed
        // TODO add your handling code here:
        //refreshBtn.setEnabled(true);
    }//GEN-LAST:event_testBtnActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed
    
    private void loadBobot(double hasilPembobotan[][]){
        int baris = hasilPembobotan.length;
        int kolom = hasilPembobotan[0].length;
        modelBobot = (DefaultTableModel) klasifikasiTable1.getModel();
        modelBobot.setColumnCount(kolom);
        
        for (int i = 0; i < baris; i++) {
            String row[] = new String[kolom];
            for (int j = 0; j < kolom; j++) {
                row[j] = String.valueOf(hasilPembobotan[i][j]);
            }
            modelBobot.addRow(row);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JPanel klasifikasi;
    private javax.swing.JTable klasifikasiTable1;
    private javax.swing.JTable klasifikasiTable2;
    private javax.swing.JButton loadBtn;
    private javax.swing.JRadioButton mnbPosRB;
    private javax.swing.JRadioButton mnbRB;
    private javax.swing.JTextField nameFile;
    private javax.swing.JButton prosesBtn;
    private javax.swing.JButton testBtn;
    // End of variables declaration//GEN-END:variables

}
